<?php

namespace Drupal\wdb_core\Routing;

use Drupal\Core\Routing\RouteSubscriberBase;
use Symfony\Component\Routing\RouteCollection;

/**
 * Listens to the dynamic route events to alter route definitions.
 */
class WdbRouteSubscriber extends RouteSubscriberBase {

  /**
   * {@inheritdoc}
   */
  protected function alterRoutes(RouteCollection $collection) {
    // Alter the canonical route for the WdbSource entity to change its access
    // requirements.
    if ($route = $collection->get('entity.wdb_source.canonical')) {
      $requirements = $route->getRequirements();

      // By default, Drupal's autogenerated entity routes use '_entity_access',
      // which typically requires administrative permissions. We remove this
      // strict requirement.
      unset($requirements['_entity_access']);

      // Instead, we set a more permissive requirement, allowing anyone with the
      // general 'access content' permission to view the page.
      $requirements['_permission'] = 'access content';

      $route->setRequirements($requirements);
    }
  }

}
